version: '3.9'
name: kel3 uas akso 
services: #service = nama-nama dan konfigurasi untuk tiap mesin virtual 
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    networks:
      - web_network
    depends_on:
      - postgres

  postgres: #service ke-2 bernama postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_data/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - web_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - web_network

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "6379:6379"
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  postgres_data:

configs:
  nginx_config:
    file: ./nginx/nginx.conf


